### ISSUE TITLE
Superfluous missing screenshot

### ISSUE THREAD

**Issue by danrabbit** [mirkobrombin/Bottles#11]
https://github.com/mirkobrombin/Bottles/blob/10740236b52a8a136ac53b35930b3d542d957ae7/data/com.github.mirkobrombin.bottles.appdata.xml#L10

Looks like an accident. There's an extra screenshots tag containing an invalid URL

**Comment by mirkobrombin** [comment]
Uops

**Comment by mirkobrombin** [comment]
Should be fixed on release [0.0.5](https://github.com/mirkobrombin/Bottles/releases/tag/0.0.5)
