### ISSUE TITLE
Proposed Arch PKGBUILD

### ISSUE THREAD

**Issue by GabMus** [mirkobrombin/Bottles#16]
I want to propose you to put Bottles on AUR, the Arch User Repository.
All you have to do is make a PKGBUILD for it, and it requires little maintenance for every update.

I also made a PKGBUILD myself to test it on my system, feel free to copy-paste it directly.

```
# Maintainers: Mirko Brombin <youremail@goes.here>, Gabriele Musco <emaildigabry@gmail.com>
# Upstream URL: https://github.com/mirkobrombin/Bottles/

pkgname=bottles-git
pkgver=0.0.8.r6.g842040c
pkgrel=1
pkgdesc='A wineprefix manager designed for elementary OS'
arch=('any')
url='https://github.com/mirkobrombin/Bottles'
license=('GPL3')
depends=('wine' 'gtk3>=3.14' 'python' 'granite' 'xterm')
makedepends=('git')
provides=('bottles')
conflicts=('bottles')
source=("bottles::git+https://github.com/mirkobrombin/Bottles")
sha256sums=('SKIP')

pkgver() {
  cd "$srcdir/bottles"
  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

package() {
  cd "$srcdir/bottles"
  mkdir -p $pkgdir/usr
  python setup.py install --prefix $pkgdir/usr
}
```

PS: Nice to see another Italian Linux dev, good job 😉

**Comment by mirkobrombin** [comment]
Sounds like a good idea! Could you add it with a PR?
PS. Thank you but I'm not really a developer only a free software supporter :smiley:

**Comment by GabMus** [comment]
> Could you add it with a PR?

Sure, but mind it'd only serve as a reference, you'd really need to put it on AUR.

**Comment by GabMus** [comment]
Uhm, I'd need to add your email

**Comment by mirkobrombin** [comment]
> Sure, but mind it'd only serve as a reference, you'd really need to put it on AUR.
Sure
