### ISSUE TITLE
Option to install different Wine versions.

### ISSUE THREAD

**Issue by giovannicaligaris** [mirkobrombin/Bottles#18]
Loving the App!

Would it be possible to have the option to install different versions of Wine just like PlayOnLinux?

http://wiki.playonlinux.com/index.php/Managing_Wine_Versions

Right now as far as I know, Bottles only has support for wine-1.6.2 (Ubuntu repository) which is an old version.

**Comment by mirkobrombin** [comment]
First of all Thanks :smile:
Next.. bottles doesn't support one specific wine version. It use the one coming with the system, so the 1.6.2 at this time.

Please read [this](https://github.com/mirkobrombin/Bottles/wiki) and [this](https://github.com/mirkobrombin/Bottles/wiki/Why-can't-choose-the-version%3F).

**Comment by giovannicaligaris** [comment]
I see what you are saying, but WineHQ offers official and stable repositories to wine-stable which I think it could be included to Bottles. 

https://wiki.winehq.org/Ubuntu

Running modern apps on Wine 1.6 might not work at all.

**Comment by mirkobrombin** [comment]
I understand and agree. So PPA need to be updated. 
In any case, it may work by installing wine-devel.
