### ISSUE TITLE
ImportError: No module named 'bottles'

### ISSUE THREAD

**Issue by Lamppost100** [mirkobrombin/Bottles#23]
I have bottles 0.1.3 installed from AppCenter:
I get error this error when i try to start:
```
$ com.github.mirkobrombin.bottles 
Traceback (most recent call last):
  File "/usr/bin/com.github.mirkobrombin.bottles", line 28, in <module>
    import bottles.main
ImportError: No module named 'bottles'
```
I've already installed libgranite-dev manually but it doesn't help.

**Comment by mirkobrombin** [comment]
Try the one below.
- Uninstall current version from AppCenter
- Install Eddy from AppCenter
- Download and unzip [this release](https://github.com/mirkobrombin/Bottles/files/1463948/com.github.mirkobrombin.bottles_0.1.4_amd64.zip)
- Open .deb with Eddy

**Comment by Lamppost100** [comment]
This version is working fine. 
Thank you for quck reply!
