### ISSUE TITLE
Having issue with updating on Elementary.

### ISSUE THREAD

**Issue by DroWnThePoor** [mirkobrombin/Bottles#28]
Errors were encountered while processing:
 /var/cache/apt/archives/com.github.mirkobrombin.bottles_0.1.8_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

I tried doing a re-install, but got the same error.
Going to try a purge, but I just found this to be an odd issue and I was hoping someone
had already reported/solved it.
I could be missing something obvious, I haven't even used Wine on this system yet, and have very little experience with it in general.

**Comment by mirkobrombin** [comment]
I can not understand the problem from the error, I need more information.
Are you using the daily branch of elementary os or the stable branch?

Try from terminal:
```apt install com.github.mirkobrombin.bottles```
and paste the output here.

Btw try this release: https://github.com/mirkobrombin/Bottles/releases/tag/0.1.5 (install with eddy)

**Comment by DroWnThePoor** [comment]
Selecting previously unselected package com.github.mirkobrombin.bottles.
(Reading database ... 748371 files and directories currently installed.)
Preparing to unpack .../com.github.mirkobrombin.bottles_0.1.8_amd64.deb ...
Unpacking com.github.mirkobrombin.bottles (0.1.8) ...
dpkg: error processing archive /var/cache/apt/archives/com.github.mirkobrombin.bottles_0.1.8_amd64.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/scalable/apps/wine.svg', which is also in package wine1.6 1:1.6.2-0ubuntu14.2

So there's two seperate issues there, they seem unrelated, but I'm not sure.

**Comment by mirkobrombin** [comment]
Tra removing usr/share/icons/hicolor/scalable/apps/wine.svg and install again, in fail paste the output here.
