### ISSUE TITLE
Use Gresource for icons

### ISSUE THREAD

**Issue by danrabbit** [mirkobrombin/Bottles#29]
Instead of instaling icons to the filesystem, you should use a Gresource. This way you can load in icons from the gresource using the same names as Wine uses without causing conflicts and your app will prefer installed versions of those icons to the built-in ones in case they're updated

**Comment by mirkobrombin** [comment]
I used this method because in other distributions wine does not install all the necessary icons. Are there any other ways to fix it?

**Comment by mirkobrombin** [comment]
Oh, I understand. I will update as soon as possible, thanks!

**Comment by mirkobrombin** [comment]
I'm using this method in v2.
